import Link from "next/link";
import { requireClinicContext } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { formatMoneyCents, formatDate } from "@/lib/format";
import { CopyButton } from "@/components/copy-button";

export default async function InvoicesPage() {
  const { clinicId } = await requireClinicContext();
  const sessions = await prisma.checkoutSession.findMany({
    where: { clinicId },
    orderBy: { createdAt: "desc" },
    take: 100,
    include: { customer: true },
  });
  return (
    <div className="space-y-4">
      <p className="text-sm text-slate-500">
        All hosted payment links and save-card links generated by this clinic.
      </p>
      <div className="card overflow-hidden">
        <table className="table">
          <thead>
            <tr>
              <th>Customer</th>
              <th>Type</th>
              <th>Amount</th>
              <th>Status</th>
              <th>Created</th>
              <th className="text-right pr-3">Link</th>
            </tr>
          </thead>
          <tbody>
            {sessions.length === 0 && (
              <tr>
                <td colSpan={6} className="text-center text-slate-500 py-10">
                  No links yet.
                </td>
              </tr>
            )}
            {sessions.map((s) => (
              <tr key={s.id}>
                <td>
                  {s.customer ? (
                    <Link
                      href={`/clinic/customers/${s.customer.id}`}
                      className="text-brand-600 hover:underline"
                    >
                      {[s.customer.firstName, s.customer.lastName]
                        .filter(Boolean)
                        .join(" ") || s.customer.email || "Customer"}
                    </Link>
                  ) : (
                    "—"
                  )}
                </td>
                <td className="text-xs capitalize">{s.mode.replace("_", " ")}</td>
                <td>
                  {s.amountCents ? formatMoneyCents(s.amountCents) : "—"}
                </td>
                <td>
                  <span
                    className={
                      s.status === "completed"
                        ? "badge-green"
                        : s.status === "expired"
                          ? "badge-slate"
                          : "badge-yellow"
                    }
                  >
                    {s.status}
                  </span>
                </td>
                <td className="text-slate-500 text-xs">
                  {formatDate(s.createdAt)}
                </td>
                <td className="text-right pr-3">
                  <CopyButton value={s.url} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
